# -*- coding: utf-8 -*-
"""Data_Crawling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-Ij873OYtrBqA2zc8qOks7zRZgKecLO
"""

!pip install BeautifulSoup4

import requests
from bs4 import BeautifulSoup

# 레시피 하나만 크롤링
import re

def RecipeCrawler(recipeId):
    url = 'https://www.10000recipe.com/recipe/' + recipeId

    response = requests.get(url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    recipe_id = [] # 레시피 id
    recipe_name = [] # 레시피 이름
    recipe_thumbnail = [] # 레시피 썸네일
    recipe_time = [] # 레시피 시간
    recipe_difficulty = [] # 레시피 난이도
    recipe_composition = [] # 레시피 구성
    recipe_ingredients = [] # 레시피 재료
    recipe_seasoning = [] # 레시피 양념
    recipe_orders = [] # 레시피 조리 순서
    recipe_photo = [] # 레시피 사진

    # 레시피 id
    recipe_id.append(recipeId)

    # 레시피 이름
    name = soup.select_one('#contents_area > div.view2_summary.st3 h3').get_text()
    recipe_name.append(name)

    # 레시피 썸네일
    thumbnail = soup.select_one('#contents_area > div.view2_pic > div.centeredcrop img')['src']
    recipe_thumbnail.append(thumbnail)

    # 레시피 시간
    time = soup.select_one('#contents_area > div.view2_summary.st3 > div.view2_summary_info > span.view2_summary_info2').get_text()
    recipe_time.append(time)

    # 레시피 난이도
    difficulty = soup.select_one('#contents_area > div.view2_summary.st3 > div.view2_summary_info > span.view2_summary_info3').get_text()
    recipe_difficulty.append(difficulty)

    # 레시피 구성 (정보 없음)
    recipe_composition.append('든든하게')

    # 레시피 재료
    ingredients = soup.select_one('#divConfirmedMaterialArea > ul:nth-child(1)')
    for tmp in ingredients.select('li'):
        item = tmp.get_text().replace('구매', '')
        item = re.sub(r'\s+', ' ', item.strip()) # 구매 링크 제외
        recipe_ingredients.append('#' + item)
    
    # 레시피 양념
    seasoning = soup.select_one('#divConfirmedMaterialArea > ul:nth-child(2)')
    for tmp in seasoning.select('li'):
        item = tmp.get_text().replace('구매', '')
        item = re.sub(r'\s+', ' ', item.strip())
        recipe_seasoning.append('#' + item)

    # 레시피 조리 순서 및 사진
    orders_photo = soup.select_one('#contents_area > div:nth-child(16)')
    steps = orders_photo.find_all('div', 'view_step_cont')
    i = 0
    for step in steps:
        i = i + 1
        order, material  = step.get_text().strip().split('.') # 조리 순서에서 주방 도구 제외
        recipe_orders.append('#' + str(i) + '. ' + order)
        recipe_photo.append('#' + step.find('img')['src'])
                                 
    recipe_all = [recipe_id, recipe_name, recipe_thumbnail, recipe_time, recipe_difficulty, recipe_composition, recipe_ingredients, recipe_seasoning, recipe_orders, recipe_photo]
    return(recipe_all)

# 연어유부초밥
RecipeCrawler(str(6909678))

# 진미채볶음
RecipeCrawler(str(6910583))