# -*- coding: utf-8 -*-
"""Data_Crawling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-Ij873OYtrBqA2zc8qOks7zRZgKecLO
"""

!pip install BeautifulSoup4

import requests
from bs4 import BeautifulSoup
import re

# 만개의 매거진 Main 레시피 id 크롤링
def MainRecipeIdCrawler(pageId):
    url = 'https://www.10000recipe.com/issue/view.html?cid=10000mag&page=' + pageId

    response = requests.get(url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    main_recipe_id = [] # Main 레시피 id

    # Main 레시피 id
    elements = soup.select('#contents_area_full > div.chef_cont > div > div > a.thumbnail')
    for element in elements:
        id = re.sub(r'\D', '', element['href'])
        main_recipe_id.append(id)

    return(main_recipe_id)

# 만개의 매거진 1페이지
MainRecipeIdCrawler(str(1))

# 만개의 매거진 Sub 레시피 id, 레시피 이름 크롤링
def SubRecipeIdCrawler(main_recipe_id):

    url = 'https://www.10000recipe.com/recipe/' + main_recipe_id

    response = requests.get(url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    sub_recipe_id = [] # Sub 레시피 id
    sub_recipe_name = [] # 레시피 이름

    # Sub 레시피 id 및 이름
    elements = soup.select('#contents_area > div > div.view_step_cont')
    for element in elements:
        id = re.sub(r'\D', '', element.find('a')['href'])
        name = element.find('a').get_text().split()[0]
        sub_recipe_id.append(id)
        sub_recipe_name.append(name)

    sub_recipe_all = [sub_recipe_id, sub_recipe_name]
    return(sub_recipe_all)

# 도시락에 빠질 수 없는 ✿유부초밥✿ 레시피 모음 (연어유부초밥, 크래미유부초밥, 명란마요유부초밥, 새우유부밥, 삼색유부초밥)
SubRecipeIdCrawler(str(6988334))

# 레시피 하나만 크롤링
def RecipeCrawler(recipeId, name):
    url = 'https://www.10000recipe.com/recipe/' + recipeId

    response = requests.get(url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    recipe_id = [] # 레시피 id
    recipe_name = [] # 레시피 이름
    recipe_thumbnail = [] # 레시피 썸네일
    recipe_time = [] # 레시피 시간
    recipe_difficulty = [] # 레시피 난이도
    recipe_composition = [] # 레시피 구성
    recipe_ingredients = [] # 레시피 재료
    recipe_seasoning = [] # 레시피 양념
    recipe_orders = [] # 레시피 조리 순서
    recipe_photo = [] # 레시피 사진

    # 레시피 id
    recipe_id.append(recipeId)

    # 레시피 이름
    recipe_name.append(name)

    # 레시피 썸네일
    thumbnail = soup.select_one('#contents_area > div.view2_pic > div.centeredcrop img')['src']
    recipe_thumbnail.append(thumbnail)

    # 레시피 시간
    time = soup.select_one('#contents_area > div.view2_summary.st3 > div.view2_summary_info > span.view2_summary_info2').get_text()
    recipe_time.append(time)

    # 레시피 난이도
    difficulty = soup.select_one('#contents_area > div.view2_summary.st3 > div.view2_summary_info > span.view2_summary_info3').get_text()
    recipe_difficulty.append(difficulty)

    # 레시피 구성 (정보 없음)
    recipe_composition.append('든든하게')

    # 레시피 재료
    elements = soup.select_one('#divConfirmedMaterialArea > ul:nth-child(1)')
    for element in elements.select('li'):
        ingredient = re.sub(r'\s+', ' ', element.get_text().replace('구매', '').strip()) # 구매 링크 제외
        recipe_ingredients.append('#' + ingredient)
    
    # 레시피 양념
    elements = soup.select_one('#divConfirmedMaterialArea > ul:nth-child(2)')
    for element in elements.select('li'):
        seasoning = re.sub(r'\s+', ' ', element.get_text().replace('구매', '').strip()) # 구매 링크 제외
        recipe_seasoning.append('#' + seasoning)

    # 레시피 조리 순서 및 사진
    elements = soup.select_one('#contents_area > div:nth-child(16)')
    elements = elements.find_all('div', 'view_step_cont')
    for i, element in enumerate(elements, start=1):
        order = element.find('div', 'media-body')
        order = ''.join(order.findAll(string=True, recursive=False)).strip() # 조리 순서에서 설명, 주방 도구 제외
        photo = element.find('img')['src']
        recipe_orders.append('#' + str(i) + '. ' + order)
        recipe_photo.append('#' + photo)
                                 
    recipe_all = [recipe_id, recipe_name, recipe_thumbnail, recipe_time, recipe_difficulty, recipe_composition, recipe_ingredients, recipe_seasoning, recipe_orders, recipe_photo]
    return(recipe_all)

# 연어유부초밥
RecipeCrawler(str(6909678), '연어유부초밥')

# 크래미유부초밥
RecipeCrawler(str(6916853), '크래미유부초밥')